![Imgur](https://i.imgur.com/h4PPC71.png)
#Data Sayns va Sunʼiy Intellekt Praktikum

#8.26. NumPy kutubxonasi boʻyicha amaliy vazifa

Topshiriqni aynan qanday funksiyalar yordamida bajarish mumkinligi `💡Ishora` koʻrinishida berilgan.

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va uni chop eting.

Versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [1]:
import numpy as np

#### 2. Raqamli qiymatlar roʻyxatini bir oʻlchovli NumPy massiviga aylantiring.

`💡Ishora` numpy.array

In [2]:
list = range(2,22,3)
arr1 = np.array(list)

#### 3. Qiymatlari noldan iborat boʻlgan toʻqqiz elementdan iborat massiv yarating.


---




`💡Ishora` np.zeros

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [5]:
arr2 = np.zeros(9)
print(arr2.size)
print(arr2.itemsize)

9
8


#### 5. NumPy kutubxonasidagi `add` funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [6]:
np.add.__doc__

"add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])\n\nAdd arguments element-wise.\n\nParameters\n----------\nx1, x2 : array_like\n    The arrays to be added.\n    If ``x1.shape != x2.shape``, they must be broadcastable to a common\n    shape (which becomes the shape of the output).\nout : ndarray, None, or tuple of ndarray and None, optional\n    A location into which the result is stored. If provided, it must have\n    a shape that the inputs broadcast to. If not provided or None,\n    a freshly-allocated array is returned. A tuple (possible only as a\n    keyword argument) must have length equal to the number of outputs.\nwhere : array_like, optional\n    This condition is broadcast over the input. At locations where the\n    condition is True, the `out` array will be set to the ufunc result.\n    Elsewhere, the `out` array will retain its original value.\n    Note that if an uninitialized `out` array is created via the defau

#### 6. Shunday vekor yaratingki u oʻn ikki oʻlchamda va qiymatlari noldan iborat boʻlsin, lekin vektorning oltinchi qiymati 1 ga teng boʻlsin.



`💡Ishora` array[12]

In [7]:
arr3 = np.zeros((4,3))
arr3[1,2] = 1

#### 7. Qiymatlari 20 dan 59 gacha boʻlgan vektor yarating.



`💡Ishora` arange

In [8]:
arr4 = np.arange(20,60)

#### 8. Vektor yarating va uni teskari oʻzgartiring, (birinchi element oxirgisi boʻlsin)



`💡Ishora` array[::-1]

In [9]:
arr5 = arr4[::-1]

#### 9. 12 dan 20 gacha boʻlgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [10]:
arr6 = np.arange(12,21).reshape(3,3)

#### 10. Quyidagi matritsadan foydalanib nolga teng boʻlmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [11]:
np.nonzero([3,7,0,0,9,0])

(array([0, 1, 4]),)

#### 11. Tasodifiy qiymatlar bilan 2x2x2 oʻlchovidagi massiv yarating.


`💡Ishora` np.random.random

In [12]:
np.random.randn(2,2,2)

array([[[ 0.46691408,  0.9444562 ],
        [-0.72779955, -0.29874038]],

       [[ 0.71561392,  0.9230067 ],
        [-0.08333471,  2.0138039 ]]])

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 oʻlchamidagi massiv yarating. Soʻng uning eng katta va eng kichik qiymatlarini toping.


`💡Ishora` min, max

In [13]:
arr7 = np.random.randn(9,9)
arr7.min()
arr7.max()

np.float64(1.9821735777648324)

#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [14]:
arr8 = (['nan', True, False, 'nan', True, True])

#### 14. Oʻlchamlari 6x3 va 3x4 boʻlgan martitsa yarating, soʻng ularning  koʻpaytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [15]:
arr11 = np.random.randn(6,3)
arr12 = np.random.randn(3,4)
np.dot(arr11, arr12)

array([[ 0.71031614,  0.42458878, -0.48858229,  0.07791429],
       [ 0.92255162,  0.48346606, -0.45739939, -0.08350571],
       [ 3.58995396,  1.3091384 , -0.3989971 , -1.23367609],
       [-0.3234605 ,  0.26053226, -0.72189409, -0.19951292],
       [ 2.81841715,  0.51694093,  0.23059738,  2.25797606],
       [-0.1310669 , -0.14936652,  0.7040208 , -2.72018929]])

#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [16]:
9

9

#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [17]:
arr111 = np.random.randn(2)
arr112 = np.random.randn(2)
print('arr111>arr112', arr111>arr112)
print('arr111>=arr112', arr111>=arr112)
print('arr111<arr112', arr111<arr112)
print('arr111<=arr112', arr111<=arr112)

arr111>arr112 [False  True]
arr111>=arr112 [False  True]
arr111<arr112 [ True False]
arr111<=arr112 [ True False]


#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [18]:
'nan'
'ZerodivisionError'
[-9.22337204e+18]

[-9.22337204e+18]

#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping.


`💡Ishora` np.intersect1d

In [19]:
arr121 = np.arange(2,6)
arr122 = np.arange(5,14)
np.intersect1d(arr121, arr122)

array([5])

#### 19. Tasodifiy sonlardan iborat boʻlgan massiv yarating, soʻng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [20]:
arr131 = np.random.randn(5)
arr132 = arr131[arr131>0]
print(arr132-(arr132%1))
print(np.floor(arr132))
print(arr132.astype(int))
print(np.trunc(arr132))


[0. 0.]
[0. 0.]
[0 0]
[0. 0.]


#### 20. Oʻlchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha boʻlsin.



`💡Ishora` np.arange

In [21]:
arr141 = np.random.randn(3,3)
arr141[:, 0] = 0
arr141[:, 1] = 1
arr141[:, 2] = 2
arr141

array([[0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.]])

#### 21. Oʻchamlari 10 boʻlgan tasodifiy vektor yarating va uni oʻsish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [22]:
arr151 = np.random.randn(10)
arr151.sort()
arr151

array([-2.46978937, -1.98026704, -1.11898272, -1.09388051, -0.75020087,
       -0.57376743, -0.53312869, -0.14849241,  0.822299  ,  1.076612  ])

#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring.

`💡Ishora` np.allclose, np.array_equal

In [23]:
A = np.random.randn(2,3)
B = np.random.randn(2,3)
print(np.allclose(A,B))
print(np.array_equal(A, B))

False
False


#### 23. Oʻlchamlari 6x3 va 3x4 matritsa tuzing va ularni oʻzaro koʻpaytiring.


`💡Ishora` np.dot or np.ones

In [24]:
arr161 = np.random.randn(6, 3)
arr162 = np.random.randn(3, 4)
np.dot(arr161, arr162)

array([[-1.99032163, -1.70535804,  1.52385745,  0.04731001],
       [ 2.33065015,  2.48804258, -1.39094602,  0.46348396],
       [-1.52617747,  0.86833754, -0.25392706, -0.69909258],
       [ 0.52825271, -2.22477226,  0.6961564 ,  0.26964462],
       [ 1.91990953, -0.59894334, -1.40827356, -0.63416216],
       [-0.14483175,  0.68150177,  0.44926465,  0.56028421]])

#### 24. Tasodifiy sonlardan iborat boʻlgan oʻlchami 5 ga teng vektor yarating, soʻng uning eng katta qiymatini 0 ga oʻzgartiring.


`💡Ishora` argmax

In [25]:
arr171 = np.random.randn(5)
arr171[arr171.argmax()] = 0

#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [26]:
bugun = np.datetime64('today')
kecha = bugun - np.timedelta64(1, 'D')
ertaga =bugun + np.timedelta64(1, 'D')
print(bugun)
print(kecha)
print(ertaga)

2025-10-10
2025-10-09
2025-10-11


#### 26. 2016 yil yanvar oyiga toʻgʻri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [27]:
np.arange('2016-01-01', '2016-02-01', dtype='datetime64[D]')

array(['2016-01-01', '2016-01-02', '2016-01-03', '2016-01-04',
       '2016-01-05', '2016-01-06', '2016-01-07', '2016-01-08',
       '2016-01-09', '2016-01-10', '2016-01-11', '2016-01-12',
       '2016-01-13', '2016-01-14', '2016-01-15', '2016-01-16',
       '2016-01-17', '2016-01-18', '2016-01-19', '2016-01-20',
       '2016-01-21', '2016-01-22', '2016-01-23', '2016-01-24',
       '2016-01-25', '2016-01-26', '2016-01-27', '2016-01-28',
       '2016-01-29', '2016-01-30', '2016-01-31'], dtype='datetime64[D]')

#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

In [28]:
arr181 = np.random.randn(5)
arr182 = arr181[arr181>0]
print(arr182-(arr182%1))
print(np.floor(arr182))
print(arr182.astype(int))
print(np.trunc(arr182))

[0. 1.]
[0. 1.]
[0 1]
[0. 1.]


#### 28. Ixtiyoriy kichik massivlar yarating, ular yigʻindisini `np.sum` funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [29]:
arr191 = np.random.randn(3,2)
arr192 = np.add.reduce(arr191)
arr193 = np.add.reduce(arr192)
arr193

np.float64(-2.883404686649701)

#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [30]:
arr200 = np.arange(1,6)
arr201 = np.zeros(len(arr200)*4)
arr201[::4] =arr200
arr201

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.,
       0., 0., 0.])

#### 30. Quyidagi `a` massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda `b` massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?

`💡Ishora` stride_tricks.as_strided

In [34]:
from numpy.lib.stride_tricks import sliding_window_view
a = np.arange(1, 15)
b = sliding_window_view(a, window_shape=4)
b

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])

#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga oʻxshash qiymatlar kiriting. Soʻng, oʻxshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [36]:
arr211 = np.arange(8)
arr211[0] = 4
arr211[6] = 4
np.argmax(np.bincount(arr211))

np.int64(4)

#### BONUS topshiriq

`💡Oʻzingiz javob berishni istagan savolni kiriting va unga javob bering.`

In [38]:
arr222 = np.arange(1,21)
arr223 = np.where(arr222%2 ==0, 'juft','toq')
arr223

array(['toq', 'juft', 'toq', 'juft', 'toq', 'juft', 'toq', 'juft', 'toq',
       'juft', 'toq', 'juft', 'toq', 'juft', 'toq', 'juft', 'toq', 'juft',
       'toq', 'juft'], dtype='<U4')

ixtiyoriy massiv yarating va butun sonlarni juft yoki toqligini tekshiring